FROM node:22.18.0-alpine

# Add user and group for security
RUN addgroup app && adduser -S -G app app

# Change to the non-root user
USER app

# Set the working directory
WORKDIR /app

# Copy package.json and yarn.lock files
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install

# Copy the rest of the application code
COPY . .

# Expose the application port
EXPOSE 3000

# Start the application
CMD ["yarn", "start"]
