version: "3.8"

services:
  # Production Service
  production:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"
    container_name: react-app-prod
    environment:
      - NODE_ENV=production
    restart:
      unless-stopped: true
  
  # Development Service
  development:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    container_name: react-app-dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    profiles:
      - dev